-- ============================================
-- 1. pgvector
-- ============================================

create extension if not exists vector;


-- ============================================
-- 2. Jobs
-- ============================================

create table if not exists public.jobs (
    id bigint generated by default as identity primary key,

    title text not null,

    company text not null,

    location text not null,

    description text not null,

    application_url text unique not null,

    embedding vector(384),

    created_at timestamp with time zone
        default timezone('utc'::text, now())
        not null
);


-- ============================================
-- 3. Users
-- ============================================

create table if not exists public.users (
    id bigint generated by default as identity primary key,

    email text unique not null,

    profile_text text,

    skills text,

    preferred_roles text,

    preferred_locations text,

    profile_embedding vector(384),

    created_at timestamp with time zone
        default timezone('utc'::text, now())
        not null
);
alter table public.users add column if not exists experience_level text;
create table if not exists public.user_jobs_delivered (
    user_id bigint REFERENCES users(id),
    job_id bigint REFERENCES jobs(id),
    PRIMARY KEY(user_id,job_id)
);


-- ============================================
-- 4. Vector matching function
-- ============================================

create or replace function match_jobs (
    query_embedding vector(384),
    match_threshold float,
    match_count int
)
returns table (
    id bigint,
    title text,
    company text,
    location text,
    application_url text,
    similarity float
)
language sql
stable
as $$
    select
        jobs.id,
        jobs.title,
        jobs.company,
        jobs.location,
        jobs.application_url,

        1 - (
            jobs.embedding <=> query_embedding
        ) as similarity

    from public.jobs

    where 1 - (
        jobs.embedding <=> query_embedding
    ) > match_threshold

    order by jobs.embedding <=> query_embedding

    limit match_count;
$$;